import type { Metadata } from 'next'
import { hasLocale } from 'next-intl'
import { Inter } from 'next/font/google'
import { routing } from '@/shared/i18n'
import { Providers } from '@/shared/providers'
import { RootLayoutProps } from '@/shared/types'
import Header from '@/widgets/header'
import './globals.css'

const interSans = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params

  const currentLocale = hasLocale(routing.locales, locale)
    ? locale
    : routing.defaultLocale

  return (
    <html lang={currentLocale} suppressHydrationWarning>
      <body className={`${interSans.variable} antialiased`}>
        <Providers>
          <div className="container mx-auto px-4 overflow-hidden min-h-full">
            <Header />
            <main>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
