import type { Metadata } from 'next'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { Geist, Geist_Mono } from 'next/font/google'
import { routing } from '@/i18n/routing'
import { ThemingProvider } from '@/providers'
import { RootLayoutProps } from '@/types'
import Header from '@/components/header'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params

  const currentLocale = hasLocale(routing.locales, locale)
    ? locale
    : routing.defaultLocale

  return (
    <html lang={currentLocale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider>
          <ThemingProvider>
            <div className="container mx-auto overflow-hidden min-h-full">
              <Header />
              <main>{children}</main>
            </div>
          </ThemingProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
