import type { Metadata } from 'next'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { Inter } from 'next/font/google'
import { routing } from '@/i18n/routing'
import { ThemingProvider } from '@/providers'
import { RootLayoutProps } from '@/types'
import Header from '@/components/header'
import './globals.css'

const interSans = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params

  const currentLocale = hasLocale(routing.locales, locale)
    ? locale
    : routing.defaultLocale

  return (
    <html lang={currentLocale} suppressHydrationWarning>
      <body className={`${interSans.variable} antialiased`}>
        <NextIntlClientProvider>
          <ThemingProvider>
            <div className="container mx-auto overflow-hidden min-h-full">
              <Header />
              <main>{children}</main>
            </div>
          </ThemingProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
